spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/my_test_springboot
    username: postgres
    password: diwa123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update