spring.application.name=dbApp
spring.datasource.url=jdbc:postgresql://localhost:5432/my_test_springboot
spring.datasource.username=postgres
spring.datasource.password=diwa123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
